### PR TITLE
filters for arrays

### PR DESCRIPTION
**Pull request by regiscamimura**

### CODE REVIEW

**Comment by stevelacey** [comment]
@regiscamimura what's happening here?

**Comment by regiscamimura** [comment]
The previous version of the ListAPI would support array parameters like `?oneToMany=1&oneToMany=2`, and there was specific logic to workaround those filters so it would produce a query using the `__in` modifier, so `one_to_many__in=[1,2]`. With the adoption of the `django-url-filter`, the syntax is different, we would do `?oneToMany__in=1,2`, which we can do and use. This change is to preserve the `?oneToMany=1&oneToMany=2` format, so that gets translated to `django-url-filter` syntax and we can use that feature.

**Comment by stevelacey** [comment]
Alright, cool, it might be worth doing something like this instead so we're not string building just for `django-url-filter` to then parse it back to what it started as.

```py
self.q_objects.add(Q(**{f"{key}__in": self.bundle[key]}), Q.AND)
```

I copied this from the search fields stuff above and maybe it's not quite right; but generally any approach where we apply the `filter` ourselves so we don't have to push it through the url filter parser is probably better.

**Comment by wadewilliams** [comment]
Why should we preserve the `?oneToMany=1&oneToMany=2` format? 

```
There should be one-- and preferably only one --obvious way to do it.
```

**Comment by regiscamimura** [comment]
I realize that we parsing and then `django-url-filter` parses it back, yeah. But I think it's preferably to not apply the `filter` ourselves after all, first, we're adding `django-url-filter` so we don't need to reinvent the wheel, secondly, it's good that we do not add special logic for this and that case, so I would keep the way it is.

===

Preserve the format because it complies with usual query string format for multiple parameters, syntax sugar and such.

**Comment by regiscamimura** [comment]
refs #48

**Comment by stevelacey** [comment]
> Why should we preserve the `?oneToMany=1&oneToMany=2` format?

That’s the format that axios will use when you pass an arrays of things in, my preference is we don’t support commas, it has just come for free in django url filter.

**Pull request merged**
